name: quantix-os
description: Bazzite for developers and power users.

base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    install:
      - virt-manager
      - edk2-ovmf
      - qemu

  - type: systemd
    system:
      enabled:
        - libvirtd

  - type: script
    snippets:
      - "wget -qO- https://git.io/papirus-icon-theme-install | sh"

  - type: default-flatpaks
    notify: true
    user:
      install:
        - com.brave.Browser

  - type: signingcd