name: quantix-os
description: Bazzite for developers and power users.

base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - type: files
    files:
      - usr: /usr
      - etc: /etc

  - type: script
    snippets:
      - "sysctl -p"
    scripts:
      - image-info.sh

  - type: rpm-ostree
    install:
      - virt-manager
      - virt-viewer
      - edk2-ovmf
      - qemu-char-spice
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-img
      - qemu-system-x86-core
      - qemu-user-binfmt
      - qemu-user-static
      - qemu
      - libXpresent
      - code
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - podman-compose
      - podman-tui
      - podmansh
      - nerd-fonts
      - adobe-source-code-pro-fonts
      - cascadia-code-fonts
      - genisoimage
      - google-droid-sans-mono-fonts
      - google-go-mono-fonts
      - ibm-plex-mono-fonts
      - jetbrains-mono-fonts-all
      - mozilla-fira-mono-fonts

  - type: systemd
    user:
      enabled:
        - quantix-user-setup
    system:
      enabled:
        - quantix-system-setup
        - docker.socket
        - podman.socket
        - swtpm-workaround
        - libvirtd

  - type: script
    snippets:
      - "wget -qO- https://git.io/papirus-icon-theme-install | sh"
      - "sed -i '/^PRETTY_NAME/s/Bazzite/Quantix/' /usr/lib/os-release"
      - "sed -i 's/bazzite_logo.svgz/quantix_logo.svgz/g' /usr/share/plasma/look-and-feel/com.valve.vapor.desktop/contents/splash/Splash.qml"
      - "sed -i 's/bazzite_logo.svgz/quantix_logo.svgz/g' /usr/share/plasma/look-and-feel/com.valve.vgui.desktop/contents/splash/Splash.qml"
      - "sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/vscode.repo"
      - "sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/docker-ce.repo"

  - type: default-flatpaks
    notify: true
    user:
      install:
        - com.brave.Browser

  - type: signing
