name: quantix-os
description: Bazzite for developers and power users.

base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - type: files
    files:
      - usr: /usr
      - etc: /etc

  - type: script
    scripts:
      - setup.sh

  - type: rpm-ostree
    install:
      - virt-manager
      - edk2-ovmf
      - qemu
      - libXpresent
      - code
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - podman-compose
      - podman-tui
      - podmansh
      - papirus-icon-theme

  - type: systemd
    user:
      enabled:
        - quantix-user-setup
    system:
      enabled:
        - quantix-system-setup
        - docker.socket
        - podman.socket
        - swtpm-workaround
        - libvirtd

  - type: script
    scripts:
      - finalise.sh

  - type: default-flatpaks
    notify: true
    user:
      install:
        - com.brave.Browser

  - type: signing
