name: quantix
description: My personal distro based on Bazzite with some nice-to-haves for developers from Aurora DX and setup for VFIO by default. Also includes some nice Dracula theming for a pleasant dark colour scheme.

base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
      - https://copr.fedorainfracloud.org/coprs/lizardbyte/stable/repo/fedora-%OS_VERSION%/lizardbyte-stable-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/codifryed/CoolerControl/repo/fedora-%OS_VERSION%/codifryed-CoolerControl-fedora-%OS_VERSION%.repo
      - vscode.repo
      - terra.repo
      - terra-mesa.repo
      - terra-extras.repo
    keys:
      - https://download.docker.com/linux/fedora/gpg
      - https://packages.microsoft.com/keys/microsoft.asc
      - https://download.copr.fedorainfracloud.org/results/lizardbyte/stable/pubkey.gpg
    install:
      - discord
      - coolercontrol
      - dotnet-sdk-9.0
      - dotnet-sdk-10.0
      - liquidctl
      - kvantum
      - adobe-source-code-pro-fonts
      - cascadia-code-fonts
      - jetbrains-mono-fonts-all
      - ibm-plex-mono-fonts
      - cockpit-machines
      - virt-manager
      - virt-viewer
      - edk2-ovmf
      - libvirt
      - qemu
      - qemu-char-spice
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-img
      - qemu-system-x86-core
      - qemu-user-binfmt
      - qemu-user-static
      - code
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - papirus-icon-theme
      - libXpresent
      - ninja-build
      - nasm
      - iasl
      - libuuid-devel
      - glib2-devel
      - pixman-devel
      - spice-protocol
      - ddrescue
      - Sunshine
      - konsole
    remove:
      - ptyxis

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - app.zen_browser.zen
          - com.vysp3r.ProtonPlus
        remove:
          - org.mozilla.firefox
          - net.davidotek.pupgui2

  - type: systemd
    system:
      enabled:
        - quantix-system-setup.service
        - docker.socket
        - libvirtd
        - swtpm-workaround
        - tailscaled.service
    user:
      enabled:
        - sunshine.service
        - quantix-user-setup.service

  - type: script
    scripts:
      - install-dracula.sh
      - install-discord-wrapper.sh
      - qtx-info.sh

  - type: initramfs

  - type: signing