name: quantix-os
description: Bazzite for developers and power users.

base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - type: files
    files:
      - usr: /usr

  - type: script
    scripts:
      - image-info.sh

  - type: rpm-ostree
    install:
      - virt-manager
      - edk2-ovmf
      - qemu

  - type: systemd
    user:
      enabled:
        - quantix-user-setup
    system:
      enabled:
        - quantix-system-setup
        - libvirtd

  - type: script
    snippets:
      - "wget -qO- https://git.io/papirus-icon-theme-install | sh"
      - "sed -i '/^PRETTY_NAME/s/Bazzite/Quantix/' /usr/lib/os-release"

  - type: default-flatpaks
    notify: true
    user:
      install:
        - com.brave.Browser

  - type: signing