#!/usr/bin/bash

if [ "${EUID:-$(id -u)}" -eq 0 ]; then
  echo "Quantix user setup ran as root user. Exiting."
  exit 0
elif [ "$(whoami)" = "sddm" ]; then
  echo "Quantix user setup ran as sddm user. Exiting."
  exit 0
fi

# Script version
readonly QNTX_VER=3
readonly QNTX_VER_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/quantix"
readonly QNTX_VER_FILE="${QNTX_VER_DIR}/qntx_version"
QNTX_VER_RAN=""

mkdir -p "${QNTX_VER_DIR}" || { echo "Error creating directory ${QNTX_VER_DIR}." >&2; exit 1; }

if [[ -f "${QNTX_VER_FILE}" ]]; then
  QNTX_VER_RAN=$(cat "${QNTX_VER_FILE}")
fi

# Run script if it has been updated
if [[ -n "${QNTX_VER_RAN}" && "${QNTX_VER}" == "${QNTX_VER_RAN}" ]]; then
    echo "Quantix user setup has already run. Exiting..."
    exit 0
fi

# Set ptyxis opacity to 1 by default
raw="$(gsettings get org.gnome.Ptyxis profile-uuids)"
uuids="$(sed -En 's|[^0-9a-z]*||g; s|([0-9a-z]{32})|\1\n|gp' <<<${raw})"
for i in ${uuids}; do
  location="org.gnome.Ptyxis.Profile:/org/gnome/Ptyxis/Profiles/${i}/"
  gsettings set "${location}" opacity "1" && \
  gsettings set "${location}" palette "dracula"; done

# Write the version
echo "${QNTX_VER}" > "${QNTX_VER_FILE}" || { echo "Error writing to ${QNTX_VER_FILE}." >&2; exit 1; }