#!/usr/bin/bash

if ! grep -q "input" /etc/group; then
    bash -c 'grep "input" /lib/group >> /etc/group'
fi
usermod -a -G input $1

if ! grep -q "libvirt" /etc/group; then
    bash -c 'grep "libvirt" /lib/group >> /etc/group'
fi
usermod -a -G libvirt $1