#!/usr/bin/bash

if [ "${EUID:-$(id -u)}" -eq 0 ]; then
  echo "Quantix user setup ran as root user. Exiting."
  exit 0
elif [ "$(whoami)" = "sddm" ]; then
  echo "Quantix user setup ran as sddm user. Exiting."
  exit 0
fi

# Script version
readonly QNTX_VER=8
readonly QNTX_VER_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/quantix"
readonly QNTX_VER_FILE="${QNTX_VER_DIR}/qntx_version"
QNTX_VER_RAN=""

mkdir -p "${QNTX_VER_DIR}" || { echo "Error creating directory ${QNTX_VER_DIR}." >&2; exit 1; }

if [[ -f "${QNTX_VER_FILE}" ]]; then
  QNTX_VER_RAN=$(cat "${QNTX_VER_FILE}")
fi

# Run script if it has been updated
if [[ -n "${QNTX_VER_RAN}" && "${QNTX_VER}" == "${QNTX_VER_RAN}" ]]; then
    echo "Quantix user setup has already run. Exiting..."
    exit 0
fi

# Enable Flathub
flatpak remote-add --if-not-exists --user flathub /usr/etc/flatpak/remotes.d/flathub.flatpakrepo
flatpak remote-modify --user --enable flathub

# Refresh fontconfig
if [[ -f "$HOME/.config/fontconfig" ]]; then
  rm -rf "$HOME/.config/fontconfig"
fi

echo 'Enabling System76-Scheduler KWin script'
kwriteconfig5 --file kwinrc --group Plugins --key kwin-system76-scheduler-integrationEnabled true

dconf load / < /etc/dconf/db/local.d/13-quantix

# Write the version
echo "${QNTX_VER}" > "${QNTX_VER_FILE}" || { echo "Error writing to ${QNTX_VER_FILE}." >&2; exit 1; }